#!/bin/bash
{% if project is not none %}
#PBS -P {{ project }}
{% endif %}
{% if project is not none %}
#PBS -q {{ queue }}
{% endif %}
{% if project is not none %}
#PBS -l ncpus={{ ncpus }}
{% endif %}
{% if project is not none %}
#PBS -l walltime={{ wtime }}
{% endif %}
{% if project is not none %}
#PBS -l other=gdata1
{% endif %}
{% if project is not none %}
#PBS -l mem={{ mem }}
{% endif %}
{#
#PBS -o {{ wdir }}
#PBS -e {{ wdir }}/logs
#}

cd {{ wdir }}

cat {{ chunk_file}} | xargs -I '{}' {{ script }}

