#!/bin/bash
# Grid engine active comments
# see comparison on https://kb.iu.edu/d/avgl

{% if queue is not none %}
#PBS -q {{ queue }}
#$ -q {{ queue }}
{% endif %}

{% if ncpus is not none %}
#PBS -l ppn={{ ncpus }}
#$ -pe ompi {{ ncpus }}
{% endif %}

{% if wtime is not none %}
#PBS -l walltime={{ wtime }}
#$ -l time={{ wtime }}
{% endif %}

{% if stdout is not none %}
#PBS -o {{ stdout }}
#$ -o {{ stdout }}
{% endif %}

{% if stderr is not none %}
#PBS -e {{ stderr }}
#$ -e {{ stderr }}
{% endif %}

{% if name is not none %}
#PBS -N {{ name }}
#$ -N {{ name }}
{% endif %}

{% if mem is not none %}
#PBS -l mem={{ mem }}
#$ -mem {{ mem }}
{% endif %}

#$ -wd {{ wdir }}
if [ -e pbs_server ]; then
        cd {{ wdir }}
fi

cat {{ chunk_file}} | xargs -I '{}' {{ script }}

